"""Add action to LearningPathItem

Revision ID: 1ab10e30a4c6
Revises: 2c706821734c
Create Date: 2026-09-01 23:26:03.533178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab10e30a4c6'
down_revision: Union[str, Sequence[str], None] = '2c706821734c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_path_items', sa.Column('action', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_path_items', 'action')
    # ### end Alembic commands ###
