"""Update quiz models

Revision ID: 2c706821734c
Revises: b117afdd4c5a
Create Date: 2026-09-01 23:19:46.175748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c706821734c'
down_revision: Union[str, Sequence[str], None] = 'b117afdd4c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('topic_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('quiz_questions', sa.Column('source_timestamp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_questions', 'source_timestamp')
    op.drop_column('quiz_attempts', 'topic_scores')
    # ### end Alembic commands ###
