"""Add transcript segments

Revision ID: 82ce0ab342bb
Revises: b57c2081ca67
Create Date: 2026-09-01 22:36:53.789073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82ce0ab342bb'
down_revision: Union[str, Sequence[str], None] = 'b57c2081ca67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('full_text', sa.Text(), nullable=False))
    op.add_column('transcripts', sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('transcripts', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('transcripts', 'segments')
    op.drop_column('transcripts', 'full_text')
    # ### end Alembic commands ###
