"""Add topic and source_timestamp to flashcards

Revision ID: b117afdd4c5a
Revises: 82ce0ab342bb
Create Date: 2026-09-01 23:10:41.625713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b117afdd4c5a'
down_revision: Union[str, Sequence[str], None] = '82ce0ab342bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('flashcards', sa.Column('source_timestamp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcards', 'source_timestamp')
    op.drop_column('flashcards', 'topic')
    # ### end Alembic commands ###
