"""Add History Models

Revision ID: e860c6d3a5fe
Revises: dc65292ddc2d
Create Date: 2026-09-02 02:50:33.460275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e860c6d3a5fe'
down_revision: Union[str, Sequence[str], None] = 'dc65292ddc2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_history_id'), 'learning_history', ['id'], unique=False)
    op.add_column('video_progress', sa.Column('completion_percentage', sa.Float(), nullable=False))
    op.add_column('video_progress', sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('video_progress', sa.Column('last_opened', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('video_progress', 'updated_at')
    op.drop_column('video_progress', 'is_completed')
    op.drop_column('video_progress', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_progress', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('video_progress', sa.Column('is_completed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('video_progress', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('video_progress', 'last_opened')
    op.drop_column('video_progress', 'last_activity')
    op.drop_column('video_progress', 'completion_percentage')
    op.drop_index(op.f('ix_learning_history_id'), table_name='learning_history')
    op.drop_table('learning_history')
    # ### end Alembic commands ###
