"""Add ExamKit model

Revision ID: ea7c5a3f7fe7
Revises: a18deeaf7e11
Create Date: 2026-09-02 02:22:10.220281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea7c5a3f7fe7'
down_revision: Union[str, Sequence[str], None] = 'a18deeaf7e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('revision_notes', sa.JSON(), nullable=False),
    sa.Column('important_questions', sa.JSON(), nullable=False),
    sa.Column('weak_topic_revision', sa.JSON(), nullable=False),
    sa.Column('final_mock_exam', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_kits_id'), 'exam_kits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_kits_id'), table_name='exam_kits')
    op.drop_table('exam_kits')
    # ### end Alembic commands ###
