"""Add teach back attempts

Revision ID: edf6c98396c9
Revises: 1ab10e30a4c6
Create Date: 2026-09-01 23:31:18.169579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edf6c98396c9'
down_revision: Union[str, Sequence[str], None] = '1ab10e30a4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teach_back_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('evaluation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('knowledge_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teach_back_attempts_id'), 'teach_back_attempts', ['id'], unique=False)
    op.drop_index(op.f('ix_teach_back_results_id'), table_name='teach_back_results')
    op.drop_table('teach_back_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teach_back_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mastery_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('knowledge_gaps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('teach_back_results_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('teach_back_results_pkey'))
    )
    op.create_index(op.f('ix_teach_back_results_id'), 'teach_back_results', ['id'], unique=False)
    op.drop_index(op.f('ix_teach_back_attempts_id'), table_name='teach_back_attempts')
    op.drop_table('teach_back_attempts')
    # ### end Alembic commands ###
